#!/bin/sh
#SBATCH --chdir=./
#SBATCH --job-name=filter
#SBATCH --nodes=1 --ntasks=1
#SBATCH --partition quanah
#SBATCH --time=48:00:00
#SBATCH --mem-per-cpu=8G
#SBATCH --array=1-45

module load intel vcftools bcftools

# define input files from helper file during genotyping
input_array=$( head -n${SLURM_ARRAY_TASK_ID} helper6.txt | tail -n1 )

# define main working directory
workdir=/lustre/scratch/brameado/Camponotus_Local_Adaptation

# run vcftools with SNP output for ADMIXTURE
vcftools --vcf ${workdir}/03_vcf/${input_array}.g.vcf --max-missing 1.0 --minQ 20 --minGQ 20 --minDP 6 --max-meanDP 60 --min-alleles 2 --max-alleles 2 --mac 1 --thin 50000 --max-maf 0.49 --remove-indels --recode --recode-INFO-all --out ${workdir}/04_filter_vcf_admixture/${input_array}

# run vcftools with SNP output for Heterozygosity Calculations
vcftools --vcf ${workdir}/03_vcf/${input_array}.g.vcf --max-missing 0.8 --minQ 20 --minGQ 20 --minDP 6 --max-meanDP 60 --min-alleles 2 --max-alleles 2 --max-maf 0.49 --remove-indels --recode --recode-INFO-all --out ${workdir}/05_filter_vcf_heterozygosity/${input_array}

#run vcftools with SNP output for GEA tests
vcftools --vcf ${workdir}/03_vcf/${input_array}.g.vcf --max-missing 0.8 --minQ 20 --minGQ 20 --minDP 6 --max-meanDP 60 --min-alleles 2 --max-alleles 2 --mac 1 --max-maf 0.49 --remove-indels --recode --recode-INFO-all --out ${workdir}/06_filter_vcf_GEA/${input_array}

# run bcftools to simplify the vcftools output for ADMIXTURE
bcftools query -f '%CHROM\t%POS\t%REF\t%ALT[\t%GT]\n ' ${workdir}/04_filter_vcf_admixture/${input_array}.recode.vcf > ${workdir}/04_filter_vcf_admixture/${input_array}.simple.vcf

# run bcftools to simplify the vcftools output for heterozygosity
bcftools query -f '%CHROM\t%POS\t%REF\t%ALT[\t%GT]\n ' ${workdir}/05_filter_vcf_heterozygosity/${input_array}.recode.vcf > ${workdir}/05_filter_vcf_heterozygosity/${input_array}.simple.vcf

# run bcftools to simplify the vcftools output for GEA
bcftools query -f '%CHROM\t%POS\t%REF\t%ALT[\t%GT]\n ' ${workdir}/06_filter_vcf_GEA/${input_array}.recode.vcf > ${workdir}/06_filter_vcf_GEA/${input_array}.simple.vcf
