#!/bin/sh
#SBATCH --chdir=./
#SBATCH --job-name=filter
#SBATCH --nodes=1 --ntasks=1
#SBATCH --partition quanah
#SBATCH --time=48:00:00
#SBATCH --mem-per-cpu=8G
#SBATCH --array=1-45

module load intel vcftools bcftools

# define input files from helper file during genotyping
input_array=$( head -n${SLURM_ARRAY_TASK_ID} helper6.txt | tail -n1 )

# define main working directory
workdir=/lustre/scratch/brameado/Camponotus_Local_Adaptation

# run vcftools with SNP output for Heterozygosity Calculations
vcftools --vcf ${workdir}/03_vcf/$modoc_het.filtered.vcf  --max-missing 0.8  --minDP 6 --max-meanDP 60 --max-alleles 2 --max-maf 0.49 --remove-indels --recode --recode-INFO-all --out ${workdir}/05_filter_vcf_heterozygosity/$modoc_het.filtered.vcf
